In [2]:
from google.colab import files
uploaded=files.upload()

In [27]:
#1
import pandas as pd
import numpy as np
data1=pd.read_excel('Lab Session Data.xlsx', sheet_name='Purchase data', usecols="B,C,D")
A=data1.to_numpy()


data2=pd.read_excel('Lab Session Data.xlsx', sheet_name='Purchase data', usecols="E")
print(data2)
C=data2.to_numpy()


print("Matrix A:")
print(A)
print("Matrix C:")
print(C)

dimensionality=A.shape[1]
print("Dimensionality of A:", dimensionality)

vector_num=A.shape[0]
print("Number of vectors in A:", vector_num)

try:
    rank_A = np.linalg.matrix_rank(A)
    print("Rank of A:", rank_A)
except Exception as e:
    print("Error calculating rank:", e)

AInv=np.linalg.pinv(A)
print("PInverse of A:")
print(AInv)

#2
X=np.dot(AInv,C)
print("Solution X:")
print(X)

#3
data2['Category']=np.where(data2['Payment (Rs)']>200, 'RICH', 'POOR')
y = data2['Category'].values
print(y)

   Payment (Rs)
0           386
1           289
2           393
3           110
4           280
5           167
6           271
7           274
8           148
9           198
Matrix A:
[[20  6  2]
 [16  3  6]
 [27  6  2]
 [19  1  2]
 [24  4  2]
 [22  1  5]
 [15  4  2]
 [18  4  2]
 [21  1  4]
 [16  2  4]]
Matrix C:
[[386]
 [289]
 [393]
 [110]
 [280]
 [167]
 [271]
 [274]
 [148]
 [198]]
Dimensionality of A: 3
Number of vectors in A: 10
Rank of A: 3
PInverse of A:
[[-0.01008596 -0.03124505  0.01013951  0.0290728   0.0182907   0.01161794
  -0.00771348  0.00095458  0.01743623 -0.00542016]
 [ 0.09059668  0.07263726  0.03172933 -0.09071908 -0.01893196 -0.06926996
   0.05675464  0.03152577 -0.07641966  0.00357352]
 [ 0.00299878  0.15874243 -0.05795468 -0.06609024 -0.06295043  0.03348017
   0.01541831 -0.01070461  0.00029003  0.05938755]]
Solution X:
[[ 1.]
 [55.]
 [18.]]
['RICH' 'RICH' 'RICH' 'POOR' 'RICH' 'POOR' 'RICH' 'RICH' 'POOR' 'POOR']


In [ ]:
#2
